driver:
  kind: modern_ebpf
falco:
  modern_ebpf:
    leastPrivileged: true
  rules_files:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/rules.d/k8s-sa-token.yaml
  json_output: true
  file_output:
    enabled: false
  stdout_output:
    enabled: true
  log_stderr: true
  log_level: notice
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi
customRules:
  k8s-sa-token.yaml: "- rule: Unauthorized K8s ServiceAccount Token Read\n  desc:\
    \ Detect attempts to inspect or harvest Kubernetes ServiceAccount JWT credentials\n\
    \  condition: >\n    open_read and\n    fd.name startswith \"/var/run/secrets/kubernetes.io/serviceaccount/token\"\
    \ and\n    not proc.name in (aws-k8s-agent, kube-proxy, amazon-ssm-agent)\n  output:\
    \ >\n    CRITICAL: Pod ServiceAccount token access attempt\n    (user=%user.name\
    \ user_id=%user.uid proc=%proc.name cmdline=%proc.cmdline\n    file=%fd.name container_id=%container.id\
    \ container_name=%container.name\n    image=%container.image.repository:%container.image.tag)\n\
    \  priority: CRITICAL\n  tags: [mitre_credential_access, t1552, kubernetes, runtime_security]"
falcosidekick:
  enabled: true
  webui:
    redis:
      storage:
        enabled: false
    enabled: false
