apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
  namespace: devsecops-system
  labels:
    app: devsecops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-api
  template:
    metadata:
      labels:
        app: devsecops-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: api
          image: devsecops-api:0.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8000
