apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: event-ingestion-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"

images:
  - name: event-ingestion-api
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/event-ingestion-api-prod
    newTag: v1.0.0
